#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#

source ~/.phrases

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

printf "\nNetwork Status\n\n"
bank=$(command ip netns exec test ping -c1 -W1 10.0.100.25 | grep -o from 2> /dev/null)
place=$(command ip netns exec test ping -c1 -W1 10.0.100.36 | grep -o from 2> /dev/null)
router0=$(command ip netns exec router ip address show dev router0 | grep -o 10.0.100.1 2> /dev/null)
if [ ! -z $place ] && [ ! -z $bank ]; then
    printf "City:          $On_IGreen  $Color_Off  $(get_secrets 40)_$(get_secrets 41)\n\n"
else
    printf "City:          $On_IRed  $Color_Off\n\n"
    if ! [ -z $router0 ]; then
        printf "\tRouter0:         $On_IGreen  $Color_Off\n\n"
    else
        printf "\tRouter0:         $On_IRed  $Color_Off\n\n"
    fi
    if ! [ -z $bank ]; then
        printf "\tBig Bank:        $On_IGreen  $Color_Off\n\n"
    else
        printf "\tBig Bank:        $On_IRed  $Color_Off\n\n"
    fi
    if ! [ -z $place ]; then 
        printf "\tFactory Donut:   $On_IGreen  $Color_Off\n\n"
    else
        printf "\tFactory Donut:   $On_IRed  $Color_Off\n\n"
    fi
fi

shop=$(command ip netns exec test ping -c1 -W1 10.0.110.196 | grep -o from 2> /dev/null)
tower=$(command ip netns exec test ping -c1 -W1 10.0.110.169 | grep -o from 2> /dev/null)
router1=$(command ip netns exec router ip address show dev router1 | grep -o 10.0.110.1 2> /dev/null)
if [ ! -z $shop ] && [ ! -z $tower ]; then
    printf "Castle:        $On_IGreen  $Color_Off  $(get_secrets 42)_$(get_secrets 43)\n\n"
    printf "\tWorkshop:        $On_IGreen  $Color_Off  Castle1Task\n\n"
    printf "\tTower:           $On_IGreen  $Color_Off  Castle2Task\n\n"
else
    printf "Castle:        $On_IRed  $Color_Off\n\n"
    if ! [ -z $router1 ]; then
        printf "\tRouter1:         $On_IGreen  $Color_Off\n\n"
    else
        printf "\tRouter1:         $On_IRed  $Color_Off\n\n"
    fi
    if [ ! -z $shop ]; then
        printf "\tWorkshop:        $On_IGreen  $Color_Off  Castle1Task\n\n"
    else
        printf "\tWorkshop:        $On_IRed  $Color_Off\n\n"
    fi
    if [ ! -z $tower ]; then 
        printf "\tTower:           $On_IGreen  $Color_Off  Castle2Task\n\n"
    else
        printf "\tTower:           $On_IRed  $Color_Off\n\n"
    fi
fi

farm=$(command ip netns exec test ping -c1 -W1 10.0.120.128 | grep -o from 2> /dev/null)
cottage=$(command ip netns exec test ping -c1 -W1 10.0.120.111 | grep -o from 2> /dev/null)
router2=$(command ip netns exec router ip address show dev router2 | grep -o 10.0.120.1 2> /dev/null)
if [ ! -z $farm ] && [ ! -z $cottage ]; then
    printf "Village:       $On_IGreen  $Color_Off  $(get_secrets 44)_$(get_secrets 45)\n\n"
    printf "\tFarm:            $On_IGreen  $Color_Off  Village1Task\n\n"
    printf "\tCottage:         $On_IGreen  $Color_Off  Village2Task\n\n"
else
    printf "Village:       $On_IRed  $Color_Off\n\n"
    if ! [ -z $router2 ]; then
        printf "\tRouter2:         $On_IGreen  $Color_Off\n\n"
    else
        printf "\tRouter2:         $On_IRed  $Color_Off\n\n"
    fi
    if [ ! -z $farm ]; then
        printf "\tFarm:            $On_IGreen  $Color_Off  Village1Task\n\n"
    else
        printf "\tFarm:            $On_IRed  $Color_Off\n\n"
    fi
    if [ ! -z $cottage ]; then 
        printf "\tCottage:         $On_IGreen  $Color_Off  Village2Task\n\n"
    else
        printf "\tCottage:         $On_IRed  $Color_Off\n\n"
    fi
fi

station=$(command ip netns exec test ping -c1 -W1 10.0.130.173 | grep -o from 2> /dev/null) 
capitol=$(command ip netns exec test ping -c1 -W1 10.0.130.121 | grep -o from 2> /dev/null)
router3=$(command ip netns exec router ip address show dev router3 | grep -o 10.0.130.1 2> /dev/null)
if [ ! -z $station ] && [ ! -z $capitol ]; then
    printf "Town:          $On_IGreen  $Color_Off  $(get_secrets 46)_$(get_secrets 47)\n\n"
    printf "\tPolice Station:  $On_IGreen  $Color_Off  Town1Task\n\n"
    printf "\tNo Bucks:        $On_IGreen  $Color_Off  Town2Task\n\n"
else
    printf "Town:          $On_IRed  $Color_Off\n\n"
    if ! [ -z $router3 ]; then
        printf "\tRouter3:         $On_IGreen  $Color_Off\n\n"
    else
        printf "\tRouter3:         $On_IRed  $Color_Off\n\n"
    fi
        if [ ! -z $station ]; then
        printf "\tPolice Station:  $On_IGreen  $Color_Off  Town1Task\n\n"
    else
        printf "\tPolice Station:  $On_IRed  $Color_Off\n\n"
    fi
    if [ ! -z $capitol ]; then 
        printf "\tNo Bucks:        $On_IGreen  $Color_Off  Town2Task\n\n"
    else
        printf "\tNo Bucks:        $On_IRed  $Color_Off\n\n"
    fi
fi
