#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#

printf "\nYou hear a loud buzz from the device and a shock emanates from it.\n"
printf "\nYou hear a whisper from the device,\n\t\"Konami\"\n\nYou take 1 damage.\n\n"
echo "0" > .correct
