#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#
source ~/.combat
if [ -f .solved ]; then
    printf "\nGreat work, you've solved this room!\n\n"
    exit 0
fi
if [ -f .correct ]; then
    COR=$(cat .correct)
    if [ $COR -eq 10 ]; then
        printf "\nConfetti falls from the ceiling and the device opens to reveal a chest\n\n"
        addTreasure "controller" "Are we allowed to include this??? Like legally?"
    else
        printf "\nYou hear a loud buzz from the device and a shock emanates from it.\n"
        printf "\nYou hear a whisper from the device,\n\t\"Konami\"\n\nYou take 1 damage.\n\n"
        echo "0" > .correct
    fi
fi
