#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#

source ~/.phrases
ONE=1
TWO=2
MYNS="village1"
MYIP="10.0.120.128"
BADIP="120.10.0.128"
MYGATEWAY="10.0.120.1"
TEST="10.0.140.42"
# $1: Namespace for the setup
# $2: IP Address for the setup
# $3: Bad IP, if there is one
# $4: Gateway Address
# $5: Location
# $6: Greeting, otherwise empty
generic_setup "$MYNS" "$MYIP" "$BADIP" "$MYGATEWAY" "Village" "$(farm_hand_greeting)"
if [ -f .done ]; then
    if ! [ -f .task_done ]; then
        if ! [ -f .first ]; then
            farm_next_task
            touch .first
        else
            SECRET="flag{farm-friends-forever}"
            printf "\nDid you get that info for me? (y / n) "
            read RESP
            if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
                printf "Great, what is it: "
                read RESP
                if [ "$RESP" = "$SECRET" ]; then
                    farm_nc_success
                    touch .task_done
                    CHECKPOINT="$(get_secrets 52)_$(get_secrets 53)"
                    sed "s/Village1Task/$CHECKPOINT/" ~/status > ~/status.tmp && mv ~/status.tmp ~/status
                    chmod +x ~/status
                else
                    farm_nc_failure
                    prompt_for_hint
                    read RESP
                    if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
                        farm_nc_hint
                    else
                        printf "Okay, if you're sure.\n\n"
                    fi
                fi
            else
                prompt_for_hint
                read RESP
                if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ]; then
                    farm_nc_hint
                else
                    printf "Okay, if you're sure.\n\n"
                fi
            fi    
        fi
    else
        complete
    fi
fi
