#!/bin/sh
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#
source ~/.combat

cat << eof

The telescope uses the associated star charts around
the room in order to provide wisdom from the stars.

To use the telescope add or remove the charts that 
it directs you to.

eof

printf "\nWould you like to make seek the stars guidance? y / n  "
read RESP
if [ "$RESP" = "y" -o "$RESP" = "Y" ];then
    STAGE=0
    if test -f .stage; then
        STAGE=$(cat .stage)
    fi
    if test -f "Messier Catalogue" && [ $STAGE -eq 0 ]; then
        printf "\nYou load up the chart and look through the telescope."
        printf "\nIn the stars, you see a figure twisted like the trunk of a tree."
        printf "\n\nTo make further predictions you'll need to create the \"Caldwell Catalogue\" chart"
        printf "\nand remove the \"Messier Catalogue\" chart\n\n"
        echo 1 > .stage
    elif [ $STAGE -eq 0 ]; then
        printf "\nThe first chart you need is the \"Messier Catalogue\"\n\n"
        printf "\nYou'll have to create that chart to use the observatory\n"
    elif test -f "Caldwell Catalogue"  && ! test -f "Messier Catalogue"  && test $STAGE -eq 1 ; then
        printf "\nYou load up the chart and look through the telescope."
        printf "\nIn the stars, you see beautiful hair spilling over a tree... weird."
        printf "\n\nTo make further predictions you'll need to create the \"Hipparcos Catalgue\" chart"
        printf "\nand remove the \"Caldwell Catalogue\" chart\n\n"
        echo 2 > .stage
    elif [ $STAGE -eq 1 ]; then
        printf "\n\nTo make further predictions you'll need to create the \"Caldwell Catalogue\" chart"
        printf "\nand remove the \"Messier Catalogue\" chart\n\n"
    elif [ -f "Hipparcos Catalgue" ] && ! [ -f "Caldwell Catalogue" ] && [ $STAGE -eq 2 ]; then
        printf "\nYou load up the chart and look through the telescope."
        printf "\nIn the stars, you see a powerful item hidden in a 'passage'."
        printf "\n\nTo make further predictions you'll need to create the \"Tycho Catalogue\" chart"
        printf "\nand remove the \"Hipparcos Catalgue\" chart\n\n"
        echo 3 > .stage
    elif [ $STAGE -eq 2 ]; then
        printf "\n\nTo make further predictions you'll need to create the \"Hipparcos Catalgue\" chart"
        printf "\nand remove the \"Caldwell Catalogue\" chart\n\n"
    elif [ -f "Tycho Catalogue" ] && ! [ -f "Hipparcos Catalgue" ] && [ $STAGE -eq 3 ]; then
        printf "\nYou load up the chart and look through the telescope."
        printf "\nIn the stars, you see a powerful item hidden in a 'passage'."
        printf "\n\nTo make further predictions you'll need to create the \"Millennium Star Atlas\" chart"
        printf "\nand remove the \"Tycho Catalogue\" chart\n\n"
        echo 4 > .stage
    elif [ $STAGE -eq 3 ]; then
        printf "\n\nTo make further predictions you'll need to create the \"Tycho Catalogue\" chart"
        printf "\nand remove the \"Hipparcos Catalgue\" chart\n\n"
    elif [ -f "Millennium Star Atlas" ] && ! [ -f "Tycho Catalogue" ] && [ $STAGE -eq 4 ]; then
        printf "\nYou load up the chart and look through the telescope."
        printf "\nIn the stars, you see a powerful item hidden in a 'passage'."
        echo 5 > .stage
        addTreasure "star" "How did this fit in a chest??"
    elif [ $STAGE -eq 4 ]; then
        printf "\n\nTo make further predictions you'll need to create the \"Millennium Star Atlas\" chart"
        printf "\nand remove the \"Tycho Catalogue\" chart\n\n"
    elif [ $STAGE -eq 5 ]; then
        printf "\nYou've exhausted what the stars can show you.\n\n"
    fi
else
    printf "\n\nMaybe some other time.\n\n"
    exit 0
fi
#
#
#
#
#
#
#
#
#
#
#
#
# Hmm, that didn't work.
