#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#
# the shepherd needs to know if the compost bin you brought him is safe for his animals

source ~/.utility

report_findings() {
    cat << EOF

Hm, are you ready to report your findings? Please, let me know, is there any 
$1 in the compost [y/n]?  

EOF
}

report_level() {
	cat << EOF

Uh oh. Well, how much is in there? Maybe it's below the acceptable levels...
How much $1 is in the compost?

EOF
}

report_correct() {
	cat << EOF

Ok, that'll play. We can work with that. Can you get back to me and let me know
if there is any $1 in the compost?

EOF

}

DDT_none() {
	cat << EOF

Are you sure there's nothing? You know, my good friend **grep** smith once told
he me could find any needle in a haystack if you just give him a "-a". That 
seems like a good place to look..

EOF
	return
}

final_correct() {
	cat << EOF

Satisfactory. You've done me a service today. Carry on. I believe the farm-hand
could use some more help sifting through those inane reports. It would be 
proper of you to lend him a hand.

EOF
}

acquaintance() {
	cat << EOF

Ahhhh, the princess. Charmed to finally make your acquaintance. I am Sult, the 
shepherd of this two-horse farm. I see you've brought me some compost. I'm 
pleased with this.

Now, I unfortunately cannot make use of any second-rate compost. The land 
deserves the absolute best. 

Can you please comb through the compost and tell me if there are any pesticides 
in there? common pesticides include "DDT", "Chlorpyrifos", and "Aldrin"

I'll give you a second to comb through the compost to check. I'm seething with 
jealousy knowing you get the honor...

EOF
}


if ! test -f .farm_done; then
	cat << no_report

Princess, as much as I am for casual conversation, I would advise you go speak 
to the head of this farm before you engage with me. 

Cheers.

no_report
elif ! test -f north-scribbles.txt; then
	cat << EOF

Princess, do you happen to know if there is any compost around here?
I believe the farm-hand mentioned something about having some on hand.
Plese let me know when you find some.

EOF
elif ! test -f .sheptalk_1; then
	acquaintance
	touch .sheptalk_1

elif ! test -f .sheptalk_2; then
	report_findings "DDT"
	read RESP
	if [ $RESP != "y" ] ; then
		DDT_none
	else
		report_level "DDT"
		read RESP
		if [ $RESP -ne $(grep -oa "DDT" compost_bin | wc -l) ]; then
			echo "Are you sure about that? Try again, I don't want to have to throw out this bin."
		else
			report_correct "Chlorpyrifos"
			touch .sheptalk_2
		fi
	fi	
elif ! test -f .sheptalk_3; then
	report_findings "Chlorpyrifos"
	read RESP
	if [ $RESP != "y" ]; then
		echo "I don't trust like that. Can you double check again for me?"
	else
		report_level "Chlorpyrifos"
		read RESP
		if [ $RESP -ne $(grep -oa "Chlorpyrifos" compost_bin | wc -l) ]; then
			echo "Are you sure about that? Try again, I don't want to have to throw out this bin."
		else
			report_correct "Aldrin"
			touch .sheptalk_3
		fi
	fi
elif ! test -f .sheptalk_4; then
	report_findings "Aldrin"
	read RESP
	if [ $RESP != "y" ]; then
		echo "I don't trust like that. Can you double check again for me?"
	else
		report_level "Aldrin"
		read RESP
		if [ $RESP -ne $(grep -oa "Aldrin" compost_bin | wc -l) ]; then
			echo "Are you sure about that? Try again, I don't want to have to throw out this bin."
		else
			final_correct
			touch .sheptalk_4
			CHECKPOINT="$(get_secrets 22)_$(get_secrets 23)"
        	printf "Checkpoint 2: $CHECKPOINT\n" >> ~/.progress
		fi
	fi
else
	cat << EOF

What are you waiting for? I am not an officer, I actually work for a living...

EOF

fi

#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Hmm, that didn't work.
