#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#

if ! grep -o necklace ~/.stats &>/dev/null; then
    cat <<eof
You have found a diamond **necklace**!"

You're pretty sure it's yours because princess is stenciled into it.
You can always check your wealth with this command:

cat ~/.stats

eof
    sed "s/Inventory:/Inventory: necklace,/; s/,$//" ~/.stats > ~/.stats.tmp && mv ~/.stats.tmp ~/.stats
else
    echo "This treasure has already been taken."
fi
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Hmm, that didn't work.
# Try moving into the mainhall, maybe you
# can come back to this treasure later!
