#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#    
# this runs after the box has been searched
# and this file has been renamed to 'emptybox'
if [ "$0" = "./emptybox" ]; then
    cat << eof

The box is empty :(

eof
else
    cat <<eof

You found it!!!

You open your box of chocolate, but it's empty!!

A note falls out onto the floor.

eof
    mv boxOfChocolates emptybox
    mv ~/.hallway ~/hallway
    mv ~/.butler ~/butler
    cat <<eof > note

#
# You think you deserve this chocolate?!?
# 
# You don't.
#
# We have secured the chocolate in a safe location.
# 
# You may want to try the library...
#

eof
    
fi
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Hmm, that didn't work.
