#!/bin/sh
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#

if ! grep -o "frying pan" ~/.stats &>/dev/null; then
    cat <<eof
You found a **frying pan**!!

As a princess you've never cooked before, but you 
can really put some velocity behind this pan.

You can always check your wealth with this command:

cat ~/.stats

eof

sed "s/Inventory:/Inventory: frying pan,/; s/,$//" ~/.stats > ~/.stats.tmp && mv ~/.stats.tmp ~/.stats
else
    echo "This treasure has already been taken."
fi
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Hmm, that didn't work.