#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#
# 
hello() {
    cat <<  EOF

Oh me?  I'm not a suspect or anything.  I came to town to get away from my
overbearing father the farmer. I ran out of money and got caught trying to 
nick some food from the carpenter. How was I supposed to know he's the 
sheriff's brother. Anyway there's no way to tell anyway I'm stuck in here so
I guess I'll just do my time.

EOF
}

hello

#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Hmm, that didn't work.
