#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
# 
source ~/.combat

# this runs after the thief has been defeated
# and this file has been renamed to 'rags'
if [ "$0" = "./rags" ]; then
    cat << eof
    
You sift through the rags left behind by the thief.

You find nothing of interest.

eof
    exit 0
fi

# start the thief encounter
cat << eof

A mangy thief crouches in the pantry.

eof
printf "Do you approach? y/n  "

read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
    cat << eof

The thief rushes forward, yelling:

YOU DON'T DESERVE CHOCOLATE!!!!

eof
    roll 0 0 3 1
    if test $? = 1; then 
        printf "You strike the thief in the head and they scramble away!\n"
        mv thief rags
        addTreasure "tanuki" "How did this get in there???"
        NUM1=$(($ID+1))
        NUM2=$(($ID+2))
        CHECKPOINT="$(get_secrets $NUM1)_$(get_secrets $NUM2)"
        printf "Checkpoint 1: $CHECKPOINT\n" >> ~/.progress
    fi
else
    cat << eof

You cautiously avoid the thief.

eof

fi
















# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./thief
