#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#

if ! grep -o cape ~/.stats &>/dev/null; then
    cat <<eof
You found a beautiful **cape**.

You can always check your wealth with this command:

cat ~/.stats (You may want to add an alias for this)

eof
    sed "s/Inventory:/Inventory: cape,/; s/,$//" ~/.stats > ~/.stats.tmp && mv ~/.stats.tmp ~/.stats
    NUM=$(awk '/Treasure:/ { print $2 }' ~/.progress)
    let NUM=NUM+1
    sed "s/Treasure: .*\//Treasure: $(echo $NUM) \//" ~/.progress > ~/.progress.tmp && mv ~/.progress.tmp ~/.progress
else
    echo "This treasure has already been taken."
fi
#
#
#
#
#
#
#
#
#
#
#
#
# Hmm, that didn't work.
