#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#

greeting() {
    cat << EOF

Guess what!?!

I've started an online business.  I'm selling my frying pan upgrades to the 
whole kingdom!

At least I would be if the network were up.  Think you can 'connect' and 
figure out what's going on?

EOF
    return
}

connected() {
cat << EOF

Great, you're in!

My computer is supposed to be at 10.0.110.196.

EOF
    return
}

prompt_for_hint() {
    cat << EOF

Did you need some help?

You can check out this manual if you'd like.  (y/n)

EOF
}

no_hint() {
    cat << EOF

If you're sure, but I'm supposed to have a meeting soon... I mean no pressure.

EOF
    return
}

ip_set() {

    cat << EOF

Silly me.  Who knows how I could have messed that up.  Thanks for fixing up my 
ip address.

EOF
    return
}

ping_success() {
    cat << EOF

Well thank goodness.  I was worried you wouldn't be able to get me connected.

Now can you make sure I can get to the test computer?  It's at 10.0.140.42.

EOF
    return
}

ping_hint() {
    cat << EOF

Hint:
You should run the command 'ping -c3 10.0.140.42'

EOF
    return
}

workshop_routed() {
    cat << EOF

Amazing!!! It connects.  Technology is something else.

So about that online business...

I tried to set up a storefront, but I can't figure out what port it's on.  Do 
you think you could help me out with that?

EOF
    return
}

wrong_connection() {
    cat << EOF

It looks like you're connected to one of the other computers in the kingdom.

EOF
    return
}

complete() {
    cat << EOF

Well it looks like you've fixed everything here.

EOF
    return
}


NS=$(command ip netns identify)
if [ -f .done ]; then
    complete
elif ! [ -f ~/.router1 ]; then
    router1_setup
elif [ -z "${NS}" ]; then
    greeting
else
    if [ "$NS" = "castle2" ]; then
        ADDR_SET=$(ip a | grep -o "10.0.110.196/24 scope global castle10")
        PING=$(cat ~/.bash_history | grep -o "ping .* 10.0.110.1")
        PING2=$(cat ~/.bash_history | grep -o "ping .* 10.0.140.42")
        ROUTE_SET=$(ip route | grep -o "default via 10.0.110.1 dev castle10")
        if ! [ -z "$ROUTE_SET" ]; then
            complete
            touch .done
            # edit .start.sh to save progress
        elif ! [ -z "$PING2" ] && [ -f .ping ]; then
            ping_aftermath
        elif [ -f .ping ]; then
            prompt_for_hint
            read RESP
            if [ "$RESP" = "y" -o "$RESP" = "Y" ];then
                ping_hint
            else
                no_hint
            fi
        elif ! [ -z "$PING" ] && ! [ -z "$ADDR_SET" ]; then
            ping_success
            touch .ping
        elif ! [ -z "$ADDR_SET" ]; then
            ip_set
        elif [ -f .connected ]; then
            prompt_for_hint
            read RESP
            if [ "$RESP" = "y" -o "$RESP" = "Y" ];then
                connected_hint
            else
                no_hint
            fi
        elif ! [ -z "${NS}" ]; then
            connected
            touch .connected
        fi
    else
        wrong_connection
    fi
fi
