#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#  
source ~/.combat

if test $(ls "Right" | wc -w) = "5"; then
    printf "\nGreat work, you soled the towers of Hanoi!!!!\n\n"

    /bin/touch .solved 
    addTreasure "HanoiTower" "This is in like every game..."
fi

