#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#  
source ~/.combat
if test -f "Sad Witch"; then
    printf "\nThe Evil Witch continues to sob as a small pool continues to form around her.\n\n"
    exit
elif test -f "Happy Witch"; then
    printf "\nThe Evil Witch laughs maniacally while holding the hair you gave her.\n\n"
    exit
fi

if ! grep -o tanuki ~/.stats &>/dev/null; then
    printf "\nYou attempt to approach the throne but you are thrown back \n\n"
    printf "\nYou see the image of a tanuki that for an unexplainable reason reminds you of the kitchens.\n\n"
    exit 0
fi

if ! grep -o hedgehog ~/.stats &>/dev/null; then
    printf "\nYou attempt to approach the throne but you are thrown back \n\n"
    printf "\nYou see the image of a hedgehog that for an unexplainable reason reminds you of the library.\n\n"
    exit 0
fi

if ! grep -o corgi ~/.stats &>/dev/null; then
    printf "\nYou attempt to approach the throne but you are thrown back \n\n"
    printf "\nYou see the image of a corgi that for an unexplainable reason reminds you of the forest.\n\n"
    exit 0
fi

if ! grep -o star ~/.stats &>/dev/null; then
    printf "\nYou attempt to approach the throne but you are thrown back \n\n"
    printf "\nYou see the image of a star that reminds you of the observatory.\n\n"
    exit 0
fi

if ! grep -o controller ~/.stats &>/dev/null; then
    printf "\nYou attempt to approach the throne but you are thrown back \n\n"
    printf "\nYou see the image of a controller that reminds you of traps.\n\n"
    exit 0
fi

if ! grep -o HanoiTower ~/.stats &>/dev/null; then
    printf "\nYou attempt to approach the throne but you are thrown back \n\n"
    printf "\nYou see the image of a tower.\n\n"
    exit 0
fi

# start the encounter
cat << eof

The shadowy figure steps into the light and it's...

An Evil Witch

The witch's skin is gnarled like the bark of a tree,
with a nose that looks reminiscent of a small tree
branch.  You even think you see some leaves dotting 
witch's dress.  Most striking of all though is the 
large bald spot on the witch's head.  When the witch
notices you they scream,

    "GIVE ME YOUR HAIR!!!!!"

eof
printf "Do you engage? y / n  "

read RESP

if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then

    roll 0 0 50 5
    if test $? = 1; then 
        cat << EOF

The Witch falls to the ground utterly defeated.

Now nothing stands between you and your reward.

Suddenly the Witch begins to sob,
    "I know I'm ugly... and evil, but I thought
    if I stole your chocolate I could trade it for 
    your beautiful princess hair... and learn how
    to love myself. *sob* "

EOF
        printf "Will you take pity on the witch and offer up your hair?  y \ n "
        read RESP
        if [ "$RESP" = "y" -o "$RESP" = "Y" ]; then
            cat << EOF

You take pity on the poor Witch and offer up your long
beautiful hair.

The witch laughs maniacally, 
    "Thank you princess, now to use my hair for evil!"

The witch runs off, but luckily she leaves behind your
chocolate... overall it's a win.

EOF
            mv ./shadowy\ figure ./Happy\ Witch
        else
            mv ./shadowy\ figure ./Sad\ Witch
            cat << EOF

You feel no pity for the evil witch.  You leave the 
witch in a puddle of their own tears and stride on 
to retrieve your chocolate.

EOF
        fi
        # create the chocolate
        cat << EOF > chocolate
#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, ask your instructor.
# We're happy to provide hints.
#
cat << eof
You take a bite of the chocolate and know 
immediately that it was all worth it.  This is 
easily the best chocolate that you have ever had.

eof

printf "Press enter to continue\n\n"
read RESP


cat << eof

Congratulations!!!!

You've completed the game.

There is so much more to learn about the terminal
and so many more ways that it can make the work 
that you do on a computer easier and more enjoyable.

You should now have the skills necessary to go even
further.

eof

EOF
        chmod +x chocolate
        NUM1=$(($ID+7))
        NUM2=$(($ID+8))
        CHECKPOINT="$(get_secrets $NUM1)_$(get_secrets $NUM2)"
        printf "Checkpoint 4: $CHECKPOINT\n" >> ~/.progress       
    fi
else
    cat << eof
You sprint away, something is clearly wrong.


eof

fi
